../../target/test/consoleArchiveDumper.o: consoleArchiveDumper.cpp \
 ../vws/ArchivePacket.h ../vws/WeatherTypes.h ../vws/Measurement.h \
 ../vws/VantageProtocolConstants.h ../vws/VantageDecoder.h \
 ../vws/VantageEepromConstants.h ../vws/VantageLogger.h \
 ../vws/VantageProtocolConstants.h ../vws/Weather.h
