../../target/test/loopDumper.o: loopDumper.cpp ../vws/LoopPacket.h \
 ../vws/Measurement.h ../vws/VantageProtocolConstants.h \
 ../vws/WeatherTypes.h ../vws/DateTimeFields.h ../vws/Loop2Packet.h \
 ../vws/VantageProtocolConstants.h ../vws/VantageDecoder.h \
 ../vws/VantageEepromConstants.h ../vws/VantageLogger.h \
 ../vws/CurrentWeather.h ../vws/Loop2Packet.h ../vws/LoopPacket.h \
 ../vws/Weather.h
