../../target/test/ArchiveVerifier.o: ArchiveVerifier.cpp \
 ../vws/ArchiveManager.h ../vws/WeatherTypes.h ../vws/ArchivePacket.h \
 ../vws/Measurement.h ../vws/DateTimeFields.h ../vws/ArchivePacket.h \
 ../vws/Weather.h
