#!/bin/bash

#
# This script must be run in the deploy directory
#

dirs="log bin archive rc node"
executables="archive-dumper/archive-dumper \
             archive-fixer/archive-fixer \
             archive-rebuilder/archive-rebuilder \
             archive-verifier/archive-verifier \
             console-archive-dumper/console-archive-dumper \
             loop-packet-dumper/loop-dumper \
             vws/vws"

scripts="backup_archive \
         start_vws \
         start_weathersense \
         start_web_server \
         start_wunderground_uploader \
         stop_weathersense"

cwd=`pwd`
dir=`basename $cwd`

if [ $dir != "deploy" ]; then
    echo "You are in the wrong directory"
    echo "This script must be run in the weathersense deploy directory!"
    exit 1
fi

if [ $# != 2 ]; then
    echo "Usage: create-deploy <version> <node directory>"
    echo "Note: Node directory should include the version number"
    exit 2
fi

version=$1
nodedir=$2

mkdir tmp
basedir=tmp
installdir=$basedir/weathersense-$version

mkdir $installdir

echo "Creating installation directories..."
for dir in $dirs; do
    mkdir $installdir/$dir
done

echo "Copying executables to $installdir/bin..."
for exe in $executables; do
    cp ../source/$exe $installdir/bin
done

echo "Copying scripts to $installdir/bin..."
for script in $scripts; do
    cp ../scripts/$script $installdir/bin
done

echo "Copying start and installation scripts..."
cp ../scripts/weathersense.rc $installdir/rc

cp ./install-weathersense.sh $basedir/install-weathersense-$version.sh
cp README $basedir

cp README.archive $installdir/archive/README

cp weathersense.cron $installdir

echo $version > $installdir/weathersense-version.txt

echo "Copying VantageConsole and VantageUpload to $installdir/node..."
if [[ -d $nodedir/VantageConsole ]] && [[ -d $nodedir/VantageUploader ]]; then
    cp -r $nodedir/VantageConsole $installdir/node
    cp -r $nodedir/VantageUploader $installdir/node
else
    echo "VantageConsole or VantageUploader directory does not exist in $nodedir"  
    rm -rf $installdir
    exit 3
fi

echo "Zipping it all up..."
cd $basedir

zip -r ../weathersense-$version.zip .

cd ..

#rm -rf $basedir

echo "Installation file created!"
