#!/bin/bash

version=4.0.0

if [ $# = 1 ]; then
    version=$1
fi

echo "Starting Vantage Console Web Server version $version"
cd /weathersense/$version/node/VantageConsole &> /dev/null
if [ $? != 0 ]; then
    echo "Directory /weathersense/$version/node/VantageConsole does not exist. Start failed"
    exit 1
fi

node ./vantage-console.js
echo "Vantage Console Web Server started"
