#!/bin/bash

version=4.1.0
device=/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0

echo Arg count $#

if [ $# = 1 ]; then
    version=$1
fi

echo "Starting VWS version $version"
cd /weathersense/$version/bin &> /dev/null

if [ $? != 0 ]; then
    echo "Directory /weathersense/$version/bin does not exist. Start failed"
    exit 1
fi

./vws $device ../archive/ ../log/vws_log
