#!/bin/bash

if [ $# != 2 ]; then
    echo "Usage: start_weathersense <version> <user>"
    exit 1
fi

sleep 5

logdir=../log
logfile=$logdir/weathersense.log

weathersense_version=$1
weathersense_user=$2

echo "Starting WeatherSense version $weathersense_version" |& tee $logfile

bindir=/weathersense/$weathersense_version/bin

cd $bindir
if [ $? != 0 ]; then
    echo "Directory $bindir does not exist. Start failed"
    exit 1
fi

echo `date` "Starting VWS" |& tee $logfile
su -l $weathersense_user -c $bindir/start_vws $weathersense_version &>> $logdir/vws.log &
echo "VWS Started" |& tee $logfile

echo `date` "Starting weather underground uploader" |& tee $logfile
su -l $weathersense_user -c $bindir/start_wunderground_uploader $weathersense_version &>> $logdir/ws_uploader.log &
echo "weather underground uploader Started" |& tee $logfile

echo `date` "Starting Vantage Web Server" |& tee $logfile
su -l $weathersense_user -c $bindir/start_web_server $weathersense_version &>> $logdir/ws_web.log &
echo "Vantage Web Server Started" |& tee $logfile

if [ `pgrep -c vws` != 1 ]; then
    echo "Warning, Vantage Console (vws) did not start"
fi

if [ `pgrep -c node` != 2 ]; then
    echo "Warning, Weather Underground Uploader and/or Vantage Web Server did not start"
fi
echo "WeatherSense version $weathersense_version started" |& tee $logfile
