#!/bin/bash

version=4.0.0

if [ $# > 0 ]; then
    version=$1
fi

echo "Starting Weather Underground Uploader version $version"
cd /weathersense/$version/node/VantageUploader &> /dev/null
if [ $? != 0 ]; then
    echo "Directory /weathersense/$version/node/VantageUploader does not exist. Start failed"
    exit 1
fi

node ./vantage-uploader.js KDELEWES163 cePrrTXh
echo "Started Weather Underground Uploader"
