#!/bin/bash

if [ $# != 2 ]; then
    echo "Usage: start_weathersense <version> <user>"
    exit 1
fi

sleep 5

logdir=../log
logfile=$logdir/weathersense.log

weathersense_version=$1
weathersense_user=$2

echo "Starting WeatherSense version $version" >> $logfile

bindir=/weathersense/$weathersense_version/bin

cd $bindir
if [ $? != 0 ]; then
    echo "Directory $bindir does not exist. Start failed"
    exit 1
fi

echo `date` "Starting VWS" >> $logfile
su -l $weathersense_user -c $bindir/start_vws $weathersense_version &>> $logdir/vws.log &
echo "VWS Started" >> $logfile

echo `date` "Starting weather underground uploader" >> $logfile
su -l $weathersense_user -c $bindir/start_wunderground_uploader $weathersense_version &>> $logdir/ws_uploader.log &
echo "weather underground uploader Started" >> $logfile

echo `date` "Starting Vantage Web Server" >> $logfile
su -l $weathersense_user -c $bindir/start_web_server $weathersense_version &>> $logdir/ws_web.log &
echo "Vantage Web Server Started" >> $logfile
