#!/bin/bash

echo "Starting Node for wunderground uploader"
cd /weathersense/development/git/Vantage-Console-Node/VantageUploader
node ./vantageUploader.js
echo "Node Started for wunderground uploader"
